const cssVar = (name: string) => `var(${name})`;

export const P_TOKEN_VALUES = {
  color: {
    neutral: {
      0: '#ffffff',
      50: '#fafaf9',
      100: '#f5f5f4',
      200: '#e7e5e4',
      300: '#d6d3d1',
      400: '#a8a29e',
      500: '#78716c',
      600: '#57534e',
      700: '#44403c',
      800: '#292524',
      900: '#1c1917',
      950: '#111111',
    },
    brand: {
      50: '#fdf2f3',
      100: '#f9dcdf',
      600: '#b63f4c',
      700: '#96313c',
    },
    accent: {
      600: '#d89062',
    },
    red: {
      50: '#fef2f2',
      100: '#fee2e2',
      600: '#dc2626',
      700: '#b91c1c',
    },
    amber: {
      50: '#fffbeb',
      100: '#fef3c7',
      600: '#d97706',
    },
    green: {
      50: '#f0fdf4',
      100: '#dcfce7',
      700: '#15803d',
    },
    blue: {
      50: '#eff6ff',
      100: '#dbeafe',
      700: '#1d4ed8',
    },
  },
  typography: {
    family: {
      sans: "'AvantGarde', sans-serif",
      serif: "'Lora', serif",
    },
    weight: {
      regular: '400',
      medium: '500',
      bold: '700',
    },
    size: {
      caption: '0.75rem',
      bodySm: '0.875rem',
      bodyMd: '1rem',
      headingSm: '1.25rem',
      headingMd: '1.5rem',
      headingMdDesktop: '2.25rem',
      headingLg: '2.5rem',
      headingXl: '4rem',
      displaySm: '7rem',
      displayMd: '4rem',
    },
    lineHeight: {
      caption: '1rem',
      bodySm: '1.25rem',
      bodyMd: '1.5rem',
      headingSm: '1.75rem',
      headingMd: '2rem',
      headingMdDesktop: '2.5rem',
      headingLg: '2.75rem',
      headingXl: '3.5rem',
      displaySm: '5.5rem',
      displayMd: '4.5rem',
    },
    letterSpacing: {
      default: '0',
      wide: '0.40em',
      heading: '-0.04em',
    },
  },
  space: {
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
  },
  radius: {
    none: '0',
    xs: '0.125rem',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    full: '9999px',
  },
  size: {
    touchMin: '2.75rem',
    controlSm: '2.25rem',
    controlMd: '2.75rem',
    controlLg: '3.5rem',
    iconSm: '1rem',
    iconMd: '1.25rem',
    iconLg: '1.5rem',
  },
  focus: {
    ringWidth: '2px',
    outlineWidth: '2px',
    ringOffset: '2px',
  },
  opacity: {
    disabled: '0.5',
  },
  shadow: {
    light: {
      sm: '0 1px 2px rgb(17 17 17 / 0.06)',
      md: '0 8px 24px rgb(17 17 17 / 0.10)',
      lg: '0 16px 40px rgb(17 17 17 / 0.14)',
    },
    dark: {
      sm: '0 1px 2px rgb(0 0 0 / 0.32)',
      md: '0 8px 24px rgb(0 0 0 / 0.36)',
      lg: '0 16px 40px rgb(0 0 0 / 0.42)',
    },
  },
  motion: {
    durationFast: '120ms',
    durationNormal: '180ms',
    durationSlow: '240ms',
    easeStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  breakpoint: {
    xs: '30rem',
    sm: '40rem',
    md: '48rem',
    lg: '64rem',
    xl: '80rem',
    '2xl': '96rem',
  },
} as const;

export const P_TOKENS = {
  values: P_TOKEN_VALUES,
  color: {
    semantic: {
      background: cssVar('--p-color-background'),
      surface: cssVar('--p-color-surface'),
      surfaceRaised: cssVar('--p-color-surface-raised'),
      surfaceSubtle: cssVar('--p-color-surface-subtle'),
      surfaceInverse: cssVar('--p-color-surface-inverse'),
      border: cssVar('--p-color-border'),
      borderSubtle: cssVar('--p-color-border-subtle'),
      borderStrong: cssVar('--p-color-border-strong'),
      text: cssVar('--p-color-text'),
      textMuted: cssVar('--p-color-text-muted'),
      textSubtle: cssVar('--p-color-text-subtle'),
      textInverse: cssVar('--p-color-text-inverse'),
      actionPrimary: cssVar('--p-color-action-primary'),
      actionPrimaryHover: cssVar('--p-color-action-primary-hover'),
      actionPrimarySubtle: cssVar('--p-color-action-primary-subtle'),
      focus: cssVar('--p-color-focus'),
      danger: cssVar('--p-color-danger'),
      dangerHover: cssVar('--p-color-danger-hover'),
      dangerSurface: cssVar('--p-color-danger-surface'),
      dangerBorder: cssVar('--p-color-danger-border'),
      warning: cssVar('--p-color-warning'),
      warningSurface: cssVar('--p-color-warning-surface'),
      warningBorder: cssVar('--p-color-warning-border'),
      success: cssVar('--p-color-success'),
      successSurface: cssVar('--p-color-success-surface'),
      successBorder: cssVar('--p-color-success-border'),
      info: cssVar('--p-color-info'),
      infoSurface: cssVar('--p-color-info-surface'),
      infoBorder: cssVar('--p-color-info-border'),
    },
  },
  typography: {
    family: {
      sans: cssVar('--p-font-family-sans'),
      serif: cssVar('--p-font-family-serif'),
    },
    weight: {
      regular: cssVar('--p-font-weight-regular'),
      medium: cssVar('--p-font-weight-medium'),
      bold: cssVar('--p-font-weight-bold'),
    },
    size: {
      caption: cssVar('--p-font-size-caption'),
      bodySm: cssVar('--p-font-size-body-sm'),
      bodyMd: cssVar('--p-font-size-body-md'),
      headingSm: cssVar('--p-font-size-heading-sm'),
      headingMd: cssVar('--p-font-size-heading-md'),
      headingMdDesktop: cssVar('--p-font-size-heading-md-desktop'),
      headingLg: cssVar('--p-font-size-heading-lg'),
      headingXl: cssVar('--p-font-size-heading-xl'),
      displaySm: cssVar('--p-font-size-display-sm'),
      displayMd: cssVar('--p-font-size-display-md'),
    },
    lineHeight: {
      caption: cssVar('--p-line-height-caption'),
      bodySm: cssVar('--p-line-height-body-sm'),
      bodyMd: cssVar('--p-line-height-body-md'),
      headingSm: cssVar('--p-line-height-heading-sm'),
      headingMd: cssVar('--p-line-height-heading-md'),
      headingMdDesktop: cssVar('--p-line-height-heading-md-desktop'),
      headingLg: cssVar('--p-line-height-heading-lg'),
      headingXl: cssVar('--p-line-height-heading-xl'),
      displaySm: cssVar('--p-line-height-display-sm'),
      displayMd: cssVar('--p-line-height-display-md'),
    },
    letterSpacing: {
      default: cssVar('--p-letter-spacing-default'),
      wide: cssVar('--p-letter-spacing-wide'),
      heading: cssVar('--p-letter-spacing-heading'),
    },
  },
  space: {
    0: cssVar('--p-space-0'),
    1: cssVar('--p-space-1'),
    2: cssVar('--p-space-2'),
    3: cssVar('--p-space-3'),
    4: cssVar('--p-space-4'),
    5: cssVar('--p-space-5'),
    6: cssVar('--p-space-6'),
    8: cssVar('--p-space-8'),
    10: cssVar('--p-space-10'),
    12: cssVar('--p-space-12'),
    16: cssVar('--p-space-16'),
    20: cssVar('--p-space-20'),
    24: cssVar('--p-space-24'),
  },
  radius: {
    none: cssVar('--p-radius-none'),
    xs: cssVar('--p-radius-xs'),
    sm: cssVar('--p-radius-sm'),
    md: cssVar('--p-radius-md'),
    lg: cssVar('--p-radius-lg'),
    full: cssVar('--p-radius-full'),
  },
  size: {
    touchMin: cssVar('--p-size-touch-min'),
    controlSm: cssVar('--p-size-control-sm'),
    controlMd: cssVar('--p-size-control-md'),
    controlLg: cssVar('--p-size-control-lg'),
    iconSm: cssVar('--p-size-icon-sm'),
    iconMd: cssVar('--p-size-icon-md'),
    iconLg: cssVar('--p-size-icon-lg'),
  },
  focus: {
    ringWidth: cssVar('--p-focus-ring-width'),
    outlineWidth: cssVar('--p-focus-outline-width'),
    ringOffset: cssVar('--p-focus-ring-offset'),
    ringColor: cssVar('--p-focus-ring-color'),
  },
  opacity: {
    disabled: cssVar('--p-opacity-disabled'),
  },
  shadow: {
    sm: cssVar('--p-shadow-sm'),
    md: cssVar('--p-shadow-md'),
    lg: cssVar('--p-shadow-lg'),
  },
  motion: {
    durationFast: cssVar('--p-duration-fast'),
    durationNormal: cssVar('--p-duration-normal'),
    durationSlow: cssVar('--p-duration-slow'),
    easeStandard: cssVar('--p-ease-standard'),
  },
  component: {
    control: {
      bg: cssVar('--p-control-bg'),
      bgHover: cssVar('--p-control-bg-hover'),
      bgFocus: cssVar('--p-control-bg-focus'),
      bgReadonly: cssVar('--p-control-bg-readonly'),
      text: cssVar('--p-control-text'),
      textMuted: cssVar('--p-control-text-muted'),
      border: cssVar('--p-control-border'),
      borderHover: cssVar('--p-control-border-hover'),
      borderFocus: cssVar('--p-control-border-focus'),
      borderError: cssVar('--p-control-border-error'),
      ring: cssVar('--p-control-ring'),
      radius: cssVar('--p-control-radius'),
      fontSize: cssVar('--p-control-font-size'),
      lineHeight: cssVar('--p-control-line-height'),
      messageFontSize: cssVar('--p-control-message-font-size'),
      messageLineHeight: cssVar('--p-control-message-line-height'),
      borderWidth: cssVar('--p-control-border-width'),
      paddingX: cssVar('--p-control-padding-x'),
      paddingY: cssVar('--p-control-padding-y'),
      messageMarginTop: cssVar('--p-control-message-margin-top'),
      transition: cssVar('--p-control-transition'),
    },
  },
  breakpoint: P_TOKEN_VALUES.breakpoint,
} as const;

export type PTokenValues = typeof P_TOKEN_VALUES;
export type PTokens = typeof P_TOKENS;
